### ISSUE TITLE
Can't enter decimal numbers for multipliers

### ISSUE THREAD

**Issue by KanyonKris** [cpyarger/Home-Assistant-Addons#29]
The UI would not allow me to enter 0.01 so I had to switch to the YAML editor to do it.

The multipliers are defined as floats so I don't understand why the UI insists on integers. Perhaps change to:
```
options:
...
  gas_multiplier: 1.0
  electric_multiplier: 1.0
  water_multiplier: 1.0
```
